config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :movies do
    member do
      get "like", to: "movies#upvote"
    end
    resources :reviews do
      member do
        get "like", to: "reviews#upvote"
      end
    end
  end

  resources :searches

  get '/profile', to: "profiles#profile"
  get '/favourites', to: "profiles#favourites"
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord

  belongs_to :user
  has_many :reviews

  acts_as_votable

  has_attached_file :image, styles: { medium: "250x350#", small: "200x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_attached_file :cover, styles: { medium: "1440x950#"}
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
    if search
      where([" title LIKE ?","%#{search}%"])
    else
      all
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  acts_as_votable
  validates :rating, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
  def search_movies
    movies = Movie.all

    movies = movies.where(["title LIKE ?", "%#{keywords}%"]) if keywords.present?
    movies = movies.where(["genre LIKE ?", genre]) if genre.present?
    movies = movies.where('year > ? AND year < ?', min_year, Movie.maximum("year")) if min_year.present?
    movies = movies.where('year > ? AND year < ?', Movie.minimum("year"), max_year) if max_year.present?
    movies = movies.where('year > ? AND year < ?', min_year, max_year) if (min_year && max_year).present?

    movies = movies.where(["director LIKE ?", "%#{director}%"]) if director.present?
    movies = movies.where(["actors LIKE ?", "%#{actor}%"]) if actor.present?

    return movies
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter

  has_many :movies
  has_many :reviews
  has_attached_file :image, styles: { medium: "200x350>", small: "300x250>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :about, :age, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :about, :age, :image])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin, except: [:index, :show, :upvote]
  before_action :find_movie, :only => [:show, :edit, :update, :delete, :upvote]

  def index
    @movies = Movie.search(params[:search]).shuffle.first(6)
    @random_movie_1 = Movie.where.not(id: @movie).order("RANDOM()")
    @random_movie_2 = Movie.where.not(id: @movie).order("RANDOM()")
    @random_movie_3 = Movie.where.not(id: @movie).order("RANDOM()")
  end

  def show
    @reviews = @movie.reviews
    @random_movie = Movie.where.not(id: @movie).order("RANDOM()").first
  end

  def new
    @movie = current_user.movies.build
  end

  def create
    @movie = current_user.movies.build(movie_params)

    if @movie.save
      flash[:notice] = "New Movie Created"
      redirect_to @movie
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      flash[:notice] = "Movie Updated"
      redirect_to @movie
    else
      render 'edit'
    end
  end

  def destroy
    @movie.destroy
    redirect_to root_path
  end

  def upvote
    @movie.upvote_by current_user
    redirect_to :back
  end

  private

  def movie_params
    params.require(:movie).permit(:image, :cover, :title, :synopsis, :director,
      :actors, :rating, :year, :month, :genre, :length, :language,
      :link_rt, :link_w, :link_fb)
  end

  def find_movie
    @movie = Movie.find(params[:id])
  end

  def authenticate_admin
    redirect_to root_path unless current_user.admin == true
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate_user!
  before_action :find_user

  def profile
    # @favourites = @user.find_liked_items
  end

  def favourites
    # @favourites = @user.find_liked_items
  end

  private

  def find_user
    @user = current_user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_movie

  def create
    @review = @movie.reviews.create(review_params)

    @review.user = current_user

    if @review.save
      redirect_to @movie, notice: 'review was successfully added'
    else
      redirect_to :back
    end
  end

  def destroy
    @review = @movie.reviews.find(params[:id])
    @review.destroy

    redirect_to movie_path(@movie)
  end

  def upvote
    @review = @movie.reviews.find(params[:id])
    @review.upvote_by current_user

    redirect_to :back
  end

  private

  def find_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:rating, :body, :movie_id, :user_id)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @movies = Movie.paginate(:page => params[:page], :per_page => 6)
    @search = Search.new
    @genres = Movie.uniq.pluck(:genre)
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
  end

  private

  def search_params
    params.require(:search).permit(:keywords, :min_year, :max_year, :genre, :director, :actor)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Mallanna|Montserrat:300", :rel => "stylesheet"}/
    %title MovieBuff
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .header-banner
      %header
        = link_to image_tag('logo.PNG', class: "nav-logo-img"), root_path, class: "nav-logo"
        .user-tools
          .nav-search
            = form_tag movies_path, :method => 'get' do
              %p.nav-search-form
                -# = button_tag( :class => "nav-search-button") do
                -#   %i.fa.fa-search.nav-search-icon
                = text_field_tag :search, params[:search], placeholder: "Quick Search"
          = link_to image_tag('browse.PNG', class: "nav-browse-img"), new_search_path, class: "nav-browse"
          .nav-expand
            %i.fa.fa-ellipsis-v.nav-expand-icon
            %nav.nav-dropdown
              %ul
                %li
                  = link_to "Home", root_path
                %li
                  = link_to "Browse", new_search_path
                %li
                %li
                  = link_to "Edit Profile", edit_user_registration_path
                -if user_signed_in?
                  %li
                    = link_to "Sign Out", destroy_user_session_path, method: :delete
                -else
                  %li
                    = link_to "Sign In", new_user_session_path
          .nav-profile
            = link_to profile_path do
              %i.fa.fa-user-circle-o.nav-profile-icon
    -if !user_signed_in?
      .banner
        .banner-text
          %h3
            %strong What do you crave on a Saturday Evening?
          %h3 Welcome to a place where good movies come to have Fun!
        .banner-actions
          %h3
            = link_to "Sign In", new_user_session_path, class: "button form-btn"
            = link_to "Sign Up", new_user_registration_path, class: "button form-sub"
    .wrapper
      = yield
    %footer
      .footer
        = link_to image_tag('logo.PNG', class: "footer-logo-img"), root_path, class: "footer-logo"
        .creator
          %h3 Created By
          %h2 Paritosh Mehta
          .icons
            %span
              = link_to "#" do
                %i.facebook.fa.fa-facebook-official
            %span
              = link_to "#" do
                %i.github.fa.fa-github-square
            %span
              = link_to "#" do
                %i.behance.fa.fa-behance-square
            %span
              = link_to "#" do
                %i.instagram.fa.fa-instagram

app/views/movies/_carousel.html.haml
#coverCarousel.carousel.slide{"data-ride" => "carousel"}
  -# / Indicators
  -# %ol.carousel-indicators
  -#   %li.active{"data-slide-to" => "0", "data-target" => "#coverCarousel"}
  -#   %li{"data-slide-to" => "1", "data-target" => "#coverCarousel"}
  -#   %li{"data-slide-to" => "2", "data-target" => "#coverCarousel"}
  -#   %li{"data-slide-to" => "3", "data-target" => "#coverCarousel"}
  / Wrapper for slides
  .carousel-inner{:role => "listbox"}
    .item.active
      = link_to (image_tag @random_movie_1[2].cover.url(:medium)), @random_movie_1[2]
      .carousel-caption.caption
        %p.title= @random_movie_1[2].title
        %p.buttons
          %span
            -# = pluralize(movie.reviews.count, "Review")
            = @random_movie_1[2].reviews.count
            %i.fa.fa-comment-o
          %span
            = @random_movie_1[2].get_likes.size
            %i.heart.fa.fa-heart
    .item
      = link_to (image_tag @random_movie_1[3].cover.url(:medium)), @random_movie_1[3]
      .carousel-caption.caption
        %p.title= @random_movie_1[3].title
        %p.buttons
          %span
            -# = pluralize(movie.reviews.count, "Review")
            = @random_movie_1[3].reviews.count
            %i.fa.fa-comment-o
          %span
            = @random_movie_1[3].get_likes.size
            %i.heart.fa.fa-heart
    .item
      = link_to (image_tag @random_movie_1[0].cover.url(:medium)), @random_movie_1[0]
      .carousel-caption.caption
        %p.title= @random_movie_1[0].title
        %p.buttons
          %span
            -# = pluralize(movie.reviews.count, "Review")
            = @random_movie_1[0].reviews.count
            %i.fa.fa-comment-o
          %span
            = @random_movie_1[0].get_likes.size
            %i.heart.fa.fa-heart
    .item
      = link_to (image_tag @random_movie_1[4].cover.url(:medium)), @random_movie_1[4]
      .carousel-caption.caption
        %p.title= @random_movie_1[4].title
        %p.buttons
          %span
            -# = pluralize(movie.reviews.count, "Review")
            = @random_movie_1[4].reviews.count
            %i.fa.fa-comment-o
          %span
            = @random_movie_1[4].get_likes.size
            %i.heart.fa.fa-heart
  / Left and right controls
  %a.left.carousel-control{"data-slide" => "prev", :href => "#coverCarousel", :role => "button"}
    %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
    %span.sr-only Previous
  %a.right.carousel-control{"data-slide" => "next", :href => "#coverCarousel", :role => "button"}
    %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
    %span.sr-only Next

app/views/movies/_form.html.haml
= simple_form_for(@movie, html: {class: 'form-horizontal'}) do |f|
  .form-inputs
    .upload
      = f.input :image
      = f.input :cover
    = f.input :title, label: false, placeholder: "Title"
    = f.input :synopsis, label: false, placeholder: "Synopsis"
    = f.input :director, label: false, placeholder: "Director"
    = f.input :actors, label: false, placeholder: "Actors"
    = f.input :rating, label: false, placeholder: "Rating"
    = f.input :year, label: false, placeholder: "Year"
    = f.input :month, label: false, placeholder: "Month"
    = f.input :genre, label: false, placeholder: "Genre"
    = f.input :length, label: false, placeholder: "Length"
    = f.input :language, label: false, placeholder: "Language"
    = f.input :link_rt, label: false, placeholder: "Link to Rotton Tomatoes"
    = f.input :link_w, label: false, placeholder: "Link to Wikepedia"
    = f.input :link_fb, label: false, placeholder: "Link to Facebook"
    = f.input :link_yt, label: false, placeholder: "Link to YouTube"
  .form-actions
    = f.button :submit, class: "button form-sub"
    = link_to "Cancel", @movie, class: "button form-btn"

app/views/movies/edit.html.haml
.sign-up-form
  .form
    %h1 Edit Movie
    = render 'form'

app/views/movies/index.html.haml
= render 'carousel'

.movies
  - @movies.each do |movie|
    .movie
      .poster
        = link_to (image_tag movie.image.url(:medium)), movie, class: "poster-img"
        .buttons
          %span
            -# = pluralize(movie.reviews.count, "Review")
            = movie.reviews.count
            %i.fa.fa-comment-o
          %span
            = movie.get_likes.size
            %i.heart.fa.fa-heart


%br
%br
%p= link_to "--> New Movie", new_movie_path
-# %p= will_paginate @collection, renderer: BootstrapPagination::Rails, previous_label: "Previous", next_label: "Next", inner_window: 1, outer_window: 0

app/views/movies/new.html.haml
.sign-up-form
  .form
    %h1 New Movie
    = render 'form'

app/views/movies/show.html.haml
.movie-cover
  = image_tag @movie.cover.url(:medium), class: "show-cover"
  .data
    .movie-info
      .title
        %h2.movie-title= @movie.title
        .buttons
          %span
            = link_to like_movie_path(@movie), mothod: :get do
              %i.heart.fa.fa-heart
            = @movie.get_likes.size
      .poster
        = image_tag @movie.image.url(:medium)
    .info
      .basic
        .genre-rating
          %p
            %b Genre:
            =@movie.genre
            -
            %b Rating:
            =@movie.rating
        .length-year
          %p= "#{@movie.length} - #{@movie.month} #{@movie.year}"
      .synopsis
        %h3
          %b Synopsis
        %p= simple_format(@movie.synopsis)
      .director-actors
        .director
          %p
            %b Director:
            =@movie.director
        .actors
          %p
            %b Actors:
            = @movie.actors
      .icons
        %span
          = link_to @movie.link_w do
            %i.wiki.fa.fa-wikipedia-w
        %span
          = link_to @movie.link_rt do
            = image_tag "tomato.png", class: "tomato"
        %span
          = link_to @movie.link_yt do
            %i.youtube.fa.fa-youtube-play
        %span
          = link_to @movie.link_fb do
            %i.facebook.fa.fa-facebook-official
-# %h2= "#{pluralize(@movie.reviews.count, 'Review')}"

- if current_user
  = render 'reviews/form'

= render @movie.reviews

.random-movie
  = link_to @random_movie do
    %h3
      %i.wiki.fa.fa-random
      Discover a Movie!

app/views/profiles/profile.html.haml
.row
  %p= "Name: #{@user.name}"

app/views/reviews/_form.html.haml
.review
  = simple_form_for [@movie, Review.new] do |f|
    #star-rating
    .review-text
      = f.input :body, label: "Review", label: false, placeholder: "Write a Review", size: "30x10"
    .submit
      = f.button :submit, "Submit"

:javascript
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });

app/views/reviews/_review.html.haml
.reviews
  .separator
  .stars
    - for i in 1..(review.rating)
      %span.fa.fa-star
  .review-body
    %p= review.body
  .review-info
    %p
      %span by #{review.user.name}
      = link_to like_movie_review_path(review.movie, review), mothod: :get do
        %i.heart.fa.fa-heart
      %span= review.get_upvotes.size
      - if user_signed_in?
        - if review.user == current_user
          %span.delete= link_to 'Delete', [review.movie, review], method: :delete, data: {confirm: 'Are You Sure?'}
-# :javascript
-#   $('.star-rating').raty({
-#         path: '/assets/',
-#         readOnly: true,
-#         score: function() {
-#               return $(this).attr('data-score');
-#       }
-#     });

app/views/searches/_form.html.haml
.advanced-search-form
  .form
    %h1.form-heading Advanced Search
    .form-fields
      = simple_form_for(@search) do |f|
        .form-inputs
          .keywords
            = f.input :keywords, label: false, placeholder: "Title"
          .year-genre
            = f.input :min_year, label: false, placeholder: "Min. Year"
            = f.input_field :genre, :collection => @genres, :prompt => "Choose Genre", :include_blank => true, input_html: {class: "dropdown-toggle"}
            = f.input :max_year, label: false, placeholder: "Max. Year"
          .director-actor
            = f.input :director, label: false, placeholder: "Director"
            = f.input :actor, label: false, placeholder: "Actor"
        .form-actions
          = f.button :submit, class: "button form-sub"

app/views/searches/new.html.haml
= render 'form'
%hr
.movies
  - @movies.each do |movie|
    .movie
      .poster
        = link_to (image_tag movie.image.url(:medium)), movie, class: "poster-img"
        .buttons
          %span
            -# = pluralize(movie.reviews.count, "Review")
            = movie.reviews.count
            %i.fa.fa-comment-o
          %span
            = movie.get_likes.size
            %i.heart.fa.fa-heart
.paginate
  %p= will_paginate @movies, renderer: BootstrapPagination::Rails, previous_label: "Previous", next_label: "Next", inner_window: 1, outer_window: 0

app/views/searches/show.html.haml

= render 'form'
%hr
.movies
  - if @search.search_movies.empty?
    %p No Records Found
  - else
    - @search.search_movies.each do |movie|
      .movie
        .poster
          = link_to (image_tag movie.image.url(:medium)), movie, class: "poster-img"
          .buttons
            %span
              -# = pluralize(movie.reviews.count, "Review")
              = movie.reviews.count
              %i.fa.fa-comment-o
            %span
              = movie.get_likes.size
              %i.heart.fa.fa-heart